apiVersion: operator.ibm.com/v1alpha1
kind: Pap
metadata:
  name: example-pap
  labels:
    app.kubernetes.io/instance: ibm-iam-operator
    app.kubernetes.io/managed-by: ibm-iam-operator
    app.kubernetes.io/name: ibm-iam-operator
spec:
  # Add fields here
  auditService:
    imageRegistry: "quay.io/opencloudio"
    imageName: "icp-audit-service"
    journalPath: "/run/systemd/journal"
  papService:
    imageRegistry: "quay.io/opencloudio"
    imageName: "iam-policy-administration"
  operatorVersion: "3.5.0"
  replicas: 1
