  
apiVersion: operator.ibm.com/v1alpha1
kind: PolicyDecision
metadata:
  name: example-policydecision
  labels:
    app.kubernetes.io/instance: ibm-iam-operator
    app.kubernetes.io/managed-by: ibm-iam-operator
    app.kubernetes.io/name: ibm-iam-operator
spec:
  auditService:
    imageRegistry: "quay.io/opencloudio"
    imageName: "icp-audit-service"
    journalPath: "/run/systemd/journal"
  imageRegistry: "quay.io/opencloudio"
  imageName: "iam-policy-decision"
  initMongodb:
    imageRegistry: "quay.io/opencloudio"
    imageName: "icp-platform-auth"
  operatorVersion: "0.14.1"
  replicas: 1
