apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-iam-operator
  labels:
     app.kubernetes.io/instance: ibm-iam-operator
     app.kubernetes.io/managed-by: ibm-iam-operator
     app.kubernetes.io/name: ibm-iam-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-iam-operator
  template:
    metadata:
      labels:
        name: ibm-iam-operator
        app.kubernetes.io/instance: ibm-iam-operator
        app.kubernetes.io/managed-by: ibm-iam-operator
        app.kubernetes.io/name: ibm-iam-operator
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.4.0"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-iam-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
        - name: ibm-iam-operator
          # Replace this with the built image name
          image: quay.io/opencloudio/ibm-iam-operator@sha256:a20391a35f3662e8884799f3553ec43545031b956f1fe19590a06c884df441f3
          command:
          - ibm-iam-operator
          imagePullPolicy: Always
          env:
            - name: AUTH_SERVICE_TAG_OR_SHA
              value: "sha256:fe712333134576b9894e70e2e3b5748916e0b3dcfb61820ab6c1133bbc8f3692"
            - name: IDENTITY_PROVIDER_TAG_OR_SHA
              value: "sha256:2b2b172f4b2fb66222a790f43ebd27d6adceff9e421150936a3d863beff5256d"
            - name: IDENTITY_MANAGER_TAG_OR_SHA
              value: "sha256:70b347289b562d4111d16b33ee0258b3aabf252edab975b5c32f2cf4f33b7548"
            - name: POLICY_ADMINISTRATION_TAG_OR_SHA
              value: "sha256:470fd0df32a5c9a2d79a19186d63234c92de0962e4f73afa3c84135cd0de8a84"
            - name: POLICY_DECISION_TAG_OR_SHA
              value: "sha256:87ea7e0b51acb55b0075ca537f27024874f356e383f60662e3f83506212cf1f1"
            - name: SECRET_WATCHER_TAG_OR_SHA
              value: "sha256:bfe42fc0463da7d30e5b83f8a5767314d991eb66c3e7a03532e20502d3c13190"
            - name: CLIENT_WATCHER_TAG_OR_SHA
              value: "sha256:0c49e27b3d4f32001e568a62abdfaecdb41f10194cf5a9ccf87ebfbdd2808fd4"
            - name: POLICY_CONTROLLER_TAG_OR_SHA
              value: "sha256:2d3029b7efc0f6dd841d61e0d454d0cdfca539aff01b57d462f11891dac32b2f"
            - name: IAM_ONBOARDING_TAG_OR_SHA
              value: "sha256:f8efc1d236be029376eb73ff57270695b94b33cceed8aee57f7fb5edc8c488e6"
            - name: AUDIT_TAG_OR_SHA
              value: "sha256:24a220374c39652f8b031637d852995bfaec5be2601f9e4c41eb1925531f466d"
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-iam-operator"
            - name: ICP_CONSOLE_URL
              valueFrom:
                configMapKeyRef:
                  name: management-ingress-info
                  key: MANAGEMENT_INGRESS_ROUTE_HOST
            - name: ICP_PROXY_URL
              valueFrom:
                configMapKeyRef:
                  name: ibmcloud-cluster-info
                  key: proxy_address
          resources:
            limits:
              cpu: 25m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 80Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true 
          volumeMounts:
            - mountPath: "/certs"
              name: cluster-ca-cert
      volumes:
        - name: cluster-ca-cert
          secret:
            defaultMode: 420
            items:
            - key: tls.key
              path: ca.key
            - key: tls.crt
              path: ca.crt
            secretName: cs-ca-certificate-secret
